import Head from 'next/head'
import axios from 'axios'
import Image from 'next/image'
import { Home, Navbar, IngredientSearch }  from '../components'
import { Inter } from '@next/font/google'
import { styles } from '../styles'

const inter = Inter({ subsets: ['latin'] })

function Main({initialData}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css"/>
      </Head>
      <main>
        {/* <Navbar/> */}
        {/* <Home initialData={initialData}/> */}
        <div className={`${styles.xPadding} h-[100vh] overflow-none`}>
        <IngredientSearch initialData={initialData}/>

        </div>
      </main>
    </>
  )
}

export async function getServerSideProps({ query }) {
    console.log('QUERY', query)
    let ingredients = []
    if (query.ingredients){
      ingredients = query.ingredients.split(',')
    }
    const res = await axios.post('https://vjj6xrqlv1.execute-api.us-west-2.amazonaws.com/production/recommend_cocktails', {'ingredients': ingredients})
    const data = await res.data.cocktails 
    return { props: { initialData:data } } 
} 

export default Main